import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import { ApolloWrapper } from "@/lib/ApolloWrapper";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "./font/ResourceHanRoundedCN-ExtraLight.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./font/ResourceHanRoundedCN-Light.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./font/ResourceHanRoundedCN-Normal.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./font/ResourceHanRoundedCN-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/ResourceHanRoundedCN-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./font/ResourceHanRoundedCN-Bold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./font/ResourceHanRoundedCN-Heavy.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body>
        <ApolloWrapper>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ApolloWrapper>
      </body>
    </html>
  );
}
